### PR TITLE
Add gauge chart to the response page

### PR DESCRIPTION
**Pull request by travisreed-wf**
I am posting this for feedback. unfortunately google recently changed the look of their gauge chart, and now it looks less academdic and more car-y

Let me know what you think. I wont be sad if you dont like it

image

### CODE REVIEW

**Comment by travisreed-wf** [comment]
@aguibert Includes db change 
```python
alter table task_response add column correctness_grade float;
```

**Comment by aguibert** [comment]
I don't think the gauge fits with the rest of the theme of the website.  What do you think of this dashboard chart lib?
image
(https://github.com/keen/dashboards)

At a quick glance this looks good for the analytics charts we are planning to do later, but for this PR I was thinking we could try the circle chart in the top right of this picture.

**Comment by aguibert** [comment]
here is a pointer to 15 more admin themes that we can use for future as well:
http://speckyboy.com/2014/05/16/free-bootstrap-admin-themes/

**Comment by travisreed-wf** [comment]
@aguibert I took out the chart and replaced it with a straight number.

We can revisit this later, but I at least wanted to get my scoring merged in.

image

**Comment by aguibert** [comment]
@travisreed-wf I agree, we can worry about styling later.  +1

**Pull request merged**
