### PR TITLE
Gradebook

### PR DESCRIPTION
**Pull request by lrohret**
Add Gradebook functionality
Gradebook pulls in courses and tasks

### CODE REVIEW

**Comment by jdmielke** [comment]
I don't see any issues +1.  Didn't you have to change something in models though?

**Comment by aguibert** [comment]
Lucas didn't want this merged in yet, last week he said he made the commit to save it or something like that.

**Comment by lrohret** [comment]
Andy is right, I pushed because my computer is having a bad time.

**Comment by travisreed-wf** [comment]
+1

**Pull request merged**
