### PR TITLE
New login page and color theme

### PR DESCRIPTION
**Pull request by aguibert**
Login page:
screen shot 2015-04-28 at 1 20 10 pm

Home Page:
screen shot 2015-04-28 at 1 20 36 pm

Task Builder:
screen shot 2015-04-28 at 1 20 46 pm

Course Page:
screen shot 2015-04-28 at 1 22 37 pm

Gradebook:
screen shot 2015-04-28 at 1 22 47 pm

### CODE REVIEW

**Comment by travisreed-wf** [comment]
I really dont like the task builder or course page.... we should probably just discuss this as a group tomorrow with nir

**Comment by aguibert** [comment]
We don't have a meeting until Thursday.  Nir wants us to deploy these changes for now so he can try it out.  I'm going to go ahead and deploy this unless anyone has any any other suggestions for color schemes.
We've been saying all semester "we realize there is a lot of white space and we'll fix that later".  I agree that this isn't the best color scheme but it is an improvement over the default white we had before.

**Comment by travisreed-wf** [comment]
I disagree that this is an improvement, but I am also a fan of white, flat websites.

Go ahead and deploy it. We can revert this or iterate upon this pull at the discretion of nir.

**Comment by AJH693** [comment]
Do you think that we should put a logo instead of just text on the login page just above the email spot?

**Comment by aguibert** [comment]
@AJH693 yes I think we should use logo's.  I was going to let you handle that in your upcoming pull since you're putting the logos in the navbar/footer already.

**Comment by aguibert** [comment]
Changed the background back to white on all pages except login -- we'll see how people like this and go from there.  Merging this in, will deploy in an hour or so.

**Pull request merged**
